### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by phoxtrot2403** [Pyhoma69/Discord-Nitro-QR#1]
I downloaded all of the versions, went thru the files and tried to run it. i even exported it again from visual studio. i tried opening the geckodriver and nothing happened. i tried to run the geckodriver and the discordqr at the same time. nothing happened, every time, the application just closes, id really appreciate some help.

**Comment by di-zay** [comment]
Yes i'd help you with that ^^
Simply install Mozilla FireFox on your computer or Update it if u arleady had it, then open discordqr and click generate, it will automatically generate a Qr code than u can copy in paste, you will have 2 minutes until the code expires

**Comment by walidpyh** [comment]
Make sure you have mozilla firefox installed
