### ISSUE TITLE
please delete this lol 

### ISSUE THREAD

**Issue by mte0** [Pyhoma69/Discord-Nitro-QR#3]
please bro delete or private this repository, keep it private!

**Comment by XKMR** [comment]
why

**Comment by walidpyh** [comment]
It's not something id take responsibility for neither discord's. This project is simply a demonstration of a type of social engineering attack that could be used against users to gain access to the accounts, taking down my repo will not help solving the root of the issue as there are many other projects doing the same. The main goal here is to spread awareness.

Regards.
