### ISSUE TITLE
Legal

### ISSUE THREAD

**Issue by wclarkey** [Pyhoma69/Discord-Nitro-QR#4]
Saying you have no responsibility will not save you, simply creating the tool has thrown you in at the deep end. People are getting hacked and scammed because of this tool. I suggest you take it down.

**Comment by walidpyh** [comment]
It's not something id take responsibility for neither discord's. This project is simply a demonstration of a type of social engineering attack that could be used against users to gain access to the accounts, taking down my repo will not help solving the root of the issue as there are many other projects doing the same. The main goal here is to spread awareness.

Regards.
