### ISSUE TITLE
I Don't Know How To Use It

### ISSUE THREAD

**Issue by jkvhjggfhjyhgggh** [Pyhoma69/Discord-Nitro-QR#6]
I don't know how to use it.

**Comment by Szpcondiscord** [comment]
same :/

**Comment by di-zay** [comment]
- Make sure to have Mozilla Firefox installed or get it updated
- Open the DiscordQR and click generate, you will have 3 minutes of valability
- Send it to your victim, when he scans it, you will get the email, token and password :)
  Enjoy
