### ISSUE TITLE
problem with code

### ISSUE THREAD

**Issue by Jorispra0** [Pyhoma69/Discord-Nitro-QR#8]
OpenQA.Selenium.NoSuchElementException: 'Unable to locate element: .qrCode\-wG6ZgU'

before using this you also need firefox installed guys, (to get a qr code)

**Comment by walidpyh** [comment]
They updated the css selector it's qrCode-2R7t9S now

**Comment by walidpyh** [comment]
Fixed in d7a3f46031d49e5e40fa7ebfeacef474df3c2952
